### ISSUE TITLE
No need of resolveLink function.

### ISSUE THREAD

**Issue by Sumit112192** [oo7coolutsav/ytdownloader#8]

**Comment by utgupta27** [comment]
Pytube module works well with this link : https://youtu.be/<Unique_Identity_of_video> 
But throws an error for some videos that have watch link : https://www.youtube.com/watch?v=<Unique_Identity_of_video>

For some videos both the links works perfectly. But usually this : https://youtu.be/<Unique_Identity_of_video> link works with most of the video. Thus, I included resolvelink() function.

You can find same issues raised by other people in pytube's repository.
